'use strict';
var globalL10n, l10n;

l10n = globalL10n = {
  button: {
    addMedia: 'Add media',
    addSlip: 'Add A Slip Up',
    backToHome: 'Back to My Homepage',
    buyOnline: 'Buy Now Online',
    cancel: 'Cancel',
    "continue": 'Continue',
    coupons: 'Coupons',
    createChallenge: 'Create challenge',
    distractMe: 'Distract Me',
    donate: 'Donate',
    done: 'Done',
    emailCoupon: 'Email Me Coupon',
    go: 'Go',
    gotIt: 'Got it!',
    keepTeam: 'No, keep me on the team',
    iSlip: 'I Slipped',
    join: 'Join',
    jumpToDay: 'Jump to Today',
    leaveTeam: 'Yes, I’m sure',
    next: 'Next',
    newCharacter: 'New Characters',
    no: 'No',
    noThanks: 'No, Thanks',
    rateApp: 'Rate This App',
    readMore: 'Read More',
    readLess: 'Read Less',
    redeem: 'Redeem',
    remindMe: 'Remind Me',
    remindLater: 'Remind Me Later',
    restart: 'Yes, Restart My Journey',
    ok: 'Ok',
    post: 'Post',
    send: 'Send',
    sendCheer: 'Send Cheer',
    sendSmiley: 'Send Smiley',
    setChallenges: 'Set Challenges',
    skip: 'Skip',
    submit: 'Submit',
    startFresh: 'Start Fresh',
    yes: 'Yes',
    qSend: 'Send ',
    qACheer: ' a Cheer!'
  },
  message: {
    success: 'Success',
    alertPass: 'Passwords must be a minimum of 4 and maximum of 12 characters. They must include 1 letter and 1 number.',
    alertRePass: 'Please enter confirm password',
    alertPassSignIn: 'Please enter a valid password',
    alertName: 'Your name can not contain numbers or special characters',
    alertEmail: 'Please enter your correct email',
    alertQuestion: 'Please choose your security question',
    alertAnswer: 'Please enter your security answer',
    alertUserName: 'User name cannot contain spaces',
    gotBadge: 'You\'ve got a badge.'
  },
  login: {
    signIn: 'Sign in',
    signUp: 'Sign up',
    forgotPass: 'Forgot Password?',
    forgotUsername: 'Forgot Username?',
    tour: 'Take a tour',
    signUp2: 'Don’t have an account? ',
    viewPrivaceyPolicy: 'See our Privacy Policy ',
    forgotMess: 'Don’t worry. Enter your username <br> below and we’ll send you <br>instructions to create a new one.',
    forgotUsernameMess: 'Don’t worry. Enter your email <br>below and we’ll send you<br> your username.',
    enterUsername: 'Enter your username:',
    enterEmail: 'Enter your email:',
    enterAnswer: 'Enter your security answer:',
    enterNewPass: 'Enter your new password:',
    textComing: '<p> You should receieve an email shortly width instructions on resetting you password.</p><p> If you still have trouble logging in, please contact <br><a href="tel:3366712123" title="phone number" class="phone"> 336 671 2123</a></p>',
    welcomeBack: ' Welcome back. It looks like it’s <br>been a while since your last visit, <br>do you want to continue your <br>journey or start fresh?  ',
    placeName: 'Your Name',
    placeUserName: 'Username',
    placeEmail: 'Your Email',
    placePass: 'Password',
    placeEnterPass: 'Password',
    placeRePass: 'Retype Your Password',
    placeQuest: 'Security Question',
    placeAnswer: 'Security Answer',
    instructionsPass: 'Passwords must be a minimum of 4 and maximum of 12 characters. They must include 1 letter and 1 number.',
    instructionsName: 'Please be aware that your username will be displayed to others if you choose to join a quit team. ',
    mustAge: ' <p>You must be 18 years of age<br> or older and a resident in the<br> UK (but not a resident in the<br> Channel Islands) to access or<br> use this application.</p><p><strong>NiQuitin</strong> Patches, Lozenges, Strips<br> and Gum are stop smoking aids.<br> Contain nicotine. Requires<br> willpower. Always read the label.<p>',
    pushBlock: '<p>weQuit by <strong>NiQuitin<strong>" <br>would like to send you <br>push notifications.</p><p>Notification may include alerts, <br>sounds and icon badges. This<br> can be configured in the<br> settings area.</p>',
    rememberMe: 'Keep me signed in'
  },
  account: {
    title: 'Pick your character',
    group1: 'My Info',
    group2: 'My Old Habit',
    group3: 'My Reason to Quit',
    group4: 'Restart My Journey',
    group5: 'Leave Quit Team',
    userName: 'Username',
    yourName: 'Your Name',
    email: 'Email',
    avatar: 'Avatar',
    password: 'Password',
    currentPass: 'Current Password',
    newPass: 'New Password',
    confirmPass: 'Confirm New Password',
    country: 'Country',
    language: 'Language',
    time: 'Your Recap Time',
    progressUpdate: 'How often do you want <br />a progress update?',
    habit1: 'You\'ve been a smoker for',
    habit2: 'You have been smoking for',
    habit3: 'You smoke',
    reason: 'We all have a reason to quit.<br>Select yours now.',
    restart: 'Are you sure you want to restart your journey? This will erase your current journey and current achivements.',
    habitLook1: 'I am looking for all all day relief from cravings',
    habitLook2: 'I am looking for craving relief when cravings strike ',
    logout: 'Logout',
    logoutText: 'Are you sure you want to log out?',
    selectValue: 'Select a value'
  },
  leaving: {
    topMess1: 'Are you sure you want to <br /> leave your Quit Team?',
    bottomMess1: 'Leaving your team means you <br> won’t be able to recieve cheers or <br> smileys any longer.',
    topMess2: 'We’re sad to see you go!',
    topMess3: 'Yay! We’re glad you stayed.',
    bottomMess2: 'If you change your mind you can re-join a Quit Team by clicking on the team in your home screen or menu navigation.'
  },
  feedBack: {
    message: '<p>Please do not report any adverse <br>effects or questions in this area. Visit <a href="http://niquitin.co.uk" title="niquitin.co.uk">niquitin.co.uk</a> for more information.</p>',
    caption: 'Give us feedback...',
    rate: 'Rate our app in the iTunes Store'
  },
  thank: {
    feedback: 'Thank you for<br/>your feedback!',
    productRating: 'Thank you<br/>for your rating!',
    donation: 'Thanks for your donation!'
  },
  habit: {
    quest1: 'How many cigarettes do you smoke a day?',
    quest2: 'What is your reason to quit?',
    quest3: 'Are you currently using nicotine replacement therapy or another product to quit?',
    quest4: 'How soon do you smoke after waking?',
    quest5: 'How many years have you been a smoker?',
    answer1: ' a day',
    answer2: ' after waking'
  },
  help: {
    info: 'Would you like to turn on <br> help messages? These <br> messages will appear once <br> as you use the app until <br> you click help again.'
  },
  landing: {
    content: 'Slip ups are part of the<br/>journey, keep going!',
    timeChallenge: 'Time Challenge',
    ofText: 'of',
    hourCompleted: 'Hours completed',
    title1: 'Team Activity',
    title2: 'Motivations and tips',
    youHave: 'You have',
    cheer: 'cheer!',
    cheers: 'cheers!',
    noCheers: 'Nothing yet. Go and cheer on a team member!',
    goToTeam: 'Go to your team page',
    QTbtn: 'Quit Team',
    QTcaption: 'Quiting can be easier together!',
    PRbtn: 'Product Reminder',
    PRcaption: 'It’s time! Check out your daily reminder',
    PRcaption2: 'Add a product to your plan and win a badge!',
    needExtra: 'Need Extra Help?',
    getToProduct: 'Get to know our products',
    quitingBtn: 'Quiting can be easier together!'
  },
  footer: {
    title: 'Thank You',
    messages: 'You\'re committed to your quit and we\'re committed to helping you. We wish you all the luck, strength and perseverance in the world. Now, let\'s make this quit happen.',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud',
    link: 'See Our Privacy Policy'
  },
  motivation: {
    textTop: 'Scroll down to view all<br/>your daily motivations',
    viewScience: 'View the science behind',
    readScience: 'Read the science behind'
  },
  science: {
    textIntro: 'Time to enjoy your favourite meal',
    readScience: 'Read the science behind',
    content: 'Now that you’ve quit, your taste buds and sense of smell have begun to improve. So why not order your favourite meal and enjoy the flavours! Lorem ipsum dolor sit amet, consectetur adipisicing elit, et quasi architecto beatae vitae dicta sunt explicabo.'
  },
  courage: {
    title: 'Slip Up Badge',
    info: 'Don\'t worry!<br/> This happens. You made it X without smoking and that\'s great. Now let\'s <br/> try to beat that.'
  },
  product: {
    getProduct: 'Get product recommendations',
    myProduct: 'My Product',
    noticeFooter: '<strong>NiQuitin</strong> Patches, Lozenges, Strips and Gums are stop smoking aids. Requires willpower. Contain nicotine. Always read the label.',
    guideText: 'Click to add the product that you are currently using. We’ll remind you daily to take this product. If you decide to try something new, simply click the icon to change your product.',
    fullDesc: 'Full Description',
    rating: 'Overall Rating',
    nickname: 'Nickname',
    titleReview: 'Title of your review',
    yourReview: 'Your review',
    averageRating: 'Average Rating',
    showMore: 'Show more reviews',
    writeReview: 'Write your review'
  },
  quitPoint: {
    startJourney: 'Start<br>Journey',
    title: 'By pushing this button you will<br> begin your Quit journey.',
    info: 'Set a reminder and start to quit when <br>you\'re prepared and ready to go.',
    characterSay: ' Say hello to your <br> new character!',
    seeOffer: 'See offer details',
    donationSection: '100 points = 5 pounds',
    donationText: 'GlaxoSmithKline is a proud sponsor of',
    donationTextColor: 'Tres Cantos Open Lab Foundation',
    donationUnderline: 'Charity Description',
    yBadgesText: 'This is your trophy room.<br>A good place to remind yourself of all<br>the small milestones along the way.',
    yPointDesc: 'You currently have',
    point: 'Points',
    yPointInfo: 'Almost there!',
    yPointInfoA: 'You need ',
    yPointInfoB: ' points to redeem for a real discount*.',
    yPointNote: '*While quantity of coupons lasts.'
  },
  signUp: {
    age: 'Age',
    bestTime: 'What time do you want your daily progress update?',
    country: 'Choose your country',
    male: 'Male',
    female: 'Female',
    language: 'Language',
    progress: 'How often do you want<br>your progress update?',
    daily: 'Daily',
    weekly: 'Weekly',
    orther: 'Every <br> Other<br> Day',
    whereHere: 'Where did you hear about the app?',
    cbTerm: 'Accept the terms and conditions',
    cbReceive: 'Receive offers and news from <strong>NiQuitin</strong>.',
    valueDefault: 'Please select...'
  },
  team: {
    joinDesc: 'Get encouragement and support <br>from other users who are on the same <br>journey by joining a quit team made<br> of other app users! You can send <br>cheers, see statistics and keep track of<br> your success together.',
    joinNote: 'Please be aware that users on your quit team will be<br> able to see your username, number of days you have<br> been smoke free, your badges and your quit points.',
    nameStats: '’s Stats',
    latestBadges: 'Latest Badges',
    cheer: 'Cheer',
    cheers: 'Cheers',
    smileys: 'Smileys',
    activityFeed: 'Activity Feed',
    teamActivity: 'Team Activity',
    receiveCheer: 'Received Cheers',
    chooseCheer: 'Choose Cheer',
    teamStat: 'Your Team Stats'
  },
  recap: {
    info: 'Great!',
    text: 'Have you had a cigarette<br /> since the last visit?'
  },
  timeline: {
    descHtml: ' Keep track of your progress and plan ahead.<br /> Is a typical moment of temptation coming up?<br /> Tap the plus icons and add it to your calendar.',
    descNoneHtml: 'Keep track of your progress and plan ahead. Is a typical moment of temptation coming up? Tap the plus icons and add it to your calendar.',
    social: 'Social',
    work: 'Work',
    personal: 'Personal',
    chooseCategory: 'Choose a category',
    party: 'Party',
    barClub: 'Bar/Club',
    outWFriends: 'Out with Friends',
    sportsEvent: 'Sports Event',
    dining: 'Dining out',
    movieNight: 'Movie Night',
    dateNight: 'Date Night',
    concert: 'Concert',
    holiday: 'Holiday',
    workEvent: 'Work event',
    presentation: 'Presentation',
    deadline: 'Deadline',
    workingLate: 'Working Late',
    stressfulDay: 'Stressful day',
    travelingFWork: 'Traveling for work',
    timeChallenge: 'Time challenge',
    stayingIn: 'Staying In',
    homeAlone: 'Home Alone',
    driving: 'Driving',
    beingSmokers: 'Being around smokers',
    morning: 'Morning',
    noon: 'Noon',
    afternoon: 'Afternoon',
    evening: 'Evening',
    whatTime: 'At what time?'
  },
  sidebarRight: {
    title: 'When is your challenge? Pick a day.',
    desc: 'Keep track of your progress and plan ahead. Is a temptation coming up? Tap the plus icons and add it to your calendar.',
    planHead: 'Plan ahead. Use your timeline to plan for, and fight through, moments of temptation.'
  },
  popup: {
    toHabit: 'Take a moment to tell us a<br> little about yourself and you\'ll <br> recieve <span>50</span> extra points!',
    creatProfile: 'Please create a quick user <br> profile to enjoy the full<br> benefits of this app.',
    challenge: 'It’s a new week!<br> Remember to record <br>any upcoming personal <br>challenges in your timeline.',
    rateAppTitle: 'Rate weQuit',
    rateAppContent: 'If you enjoy using this app would you mind taking a moment to rate it? It won’t take more than a minute. Thanks!',
    change: 'You have already listed a product that you are using. Would you like to change the product based on our recommendation?',
    informationTop: 'Based on the infomation <br>you\'ve provided, we<br> recommend that<br> ',
    informationBottom: ' might be right for you.',
    recommend: 'You are already using the product that we\'d recommend for you!',
    firstOne: 'You are the first one here,<br> but not for long!<br> We\'ll notify you as more<br> people join your team.',
    notFull: 'Your team isn\'t full quite yet.<br> We\'ll let you know as <br>more people join.',
    getPass: 'Your request has been sent to the email provided. ',
    reminder: 'Thank you! <br> We\'ll send you a reminder soon.',
    slipUp: 'Slip ups are part of the <br>journey so if you smoked a <br>cigarette let us know and <br>keep on trying to quit.',
    alertSlip: 'Not your best attempt. Give it a think and give it another go. Restart your journey?'
  }
};

//# sourceMappingURL=static-content.js.map
